server:
  port: 7001

#Eureka配置
eureka:
  instance:
    hostname: eureka7001.com  # eureka服务端的实例名字
  client:
    register-with-eureka: false #表示是否向eureka注册中心注册自己
    fetch-registry: false # 如果为false 表示自己为注册中心
    service-url:  # 监控地址
      defaultZone: http://eureka7002.com:7002/eureka/